allowed-enchants:
  all:
    - protection
    - efficiency
    - fortune
    - luck_of_the_sea
    - lure
    - silk_touch
  armor:
    - protection
  tools:
    - unbreaking
max-levels:
  protection: 1