name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.${project.name}Plugin
author: PureGero
api-version: 1.18
commands:
  blockenchants:
    description: Block enchants commands
    permission: blockenchants
permissions:
  blockenchants:
    default: op